inherit_from:
  - https://raw.githubusercontent.com/cookpad/global-style-guides/main/.rubocop.ruby.yml

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Naming/MemoizedInstanceVariableName:
  Enabled: false