#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "jiminy/setup"
require "jiminy/cli"
require "jiminy/reporting"

load "./config/initializers/jiminy.rb"

Jiminy::CLI.start
